### ISSUE TITLE
Transition order

### ISSUE THREAD

**Issue by silvestreh** [mongkuen/gatsby-plugin-page-transitions#4]
Couldn't find it in the docs, so I thought I might as well ask: Is it possible to show the entering page before leaving the current page?

I'm trying to reveal the entering page using a clipping mask and I'd like to do it on top of the current page.

**Comment by mongkuen** [comment]
I don't think this is what you'd want to use then. I'm not totally sure how you would implement what you're describing, because we're essentially 

1. holding the page navigation
2. transitioning out the current page
3. navigate to the next page
4. transitioning the next page in

What you're describing is something completely different, I imagine you'll have to use a more custom approach.

**Comment by silvestreh** [comment]
Thanks @mongkuen! I'll keep looking 😄
